---
# tasks file for mysql
# Installing packages for MySQL
- name: Installing packages for MySQL
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python3-pymysql

- name: Starting and enabling MySQL to run on startup  
  service: name=mysql state=started enabled=true

- name: Creating database for Wordpress application 
  mysql_db: 
    name: "{{ wp_db_name }}" 
    state: present 
    login_user: root 
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Creating database user for Wordpress application
  mysql_user:
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ wp_db_username }}"
    password: "{{ wp_db_userpassword }}" 
    state: present
    priv: "{{ wp_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"

- name: Reloading privilege tables
  mysql_query: 
    login_user: root
    login_db: "{{ wp_db_name }}"
    query: FLUSH PRIVILEGES
    login_unix_socket: /var/run/mysqld/mysqld.sock
